Changed a lot

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,91 +1,71 @@
 #!/bin/bash
+set -e
 
-read -p "Your main user account name please? " LOCALUSER
-
+# Check if the user is root.
 if [ $USER != "root" ]; then
 	echo "Please run the script by root user."
-	echo "Either su - root or sudo su"
 	exit
 fi
+
+# Update and Upgrade the system system first
+dpkg --add-architecture i386 # for running steam
 apt update
+apt upgrade -yyq
+
+# Check if gdebi and xargs is pre-installed. If not, go ahead and install!
 dpkg -l | grep -qw gdebi || apt install -yyq gdebi
+dpkg -l | grep -qw xargs || apt install -yyq xargs
 
-# First, let's install a bunch of software:
-apt install -yqq simplescreenrecorder vlc gthumb gimp \
-synaptic git timeshift htop curl wget mtr resolvconf openvpn \
-grsync gparted handbrake audacity vim vim-gtk \
-python3-setuptools python3-pip python3-scapy aircrack-ng nmap \
-gufw default-jdk default-jre
-
-# Install all local .deb packages, if available:
-if [ -d "/home/$LOCALUSER/Downloads" ]; then
-	echo "Installing local .deb packages..."
-	pushd /home/$LOCALUSER/Downloads
-	#Download Tunnelbear OpenVPN configs
-	wget https://s3.amazonaws.com/tunnelbear/linux/openvpn.zip && chown $LOCALUSER. openvpn.zip
-	for FILE in ./*.deb
-    do
-        gdebi -n "$FILE"
-    done
-	popd
+# Install Chrome.
+if [ -f ./chrome.sh ]
+then
+/bin/bash ./chrome.sh
 else
-	echo $'\n'$"WARNING! There's no ~/Downloads directory."
-	echo "Local .deb packages can't be automatically installed."
-	sleep 3
+echo -e "\nchrome.sh not found!"
 fi
 
-# Install Google Chrome:
-mkdir /tmp/chrome
-pushd /tmp/chrome
-wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
-gdebi -n google-chrome-stable_current_amd64.deb
-popd
-rm -rf /tmp/chrome
+# Install Discord.
+if [ -f ./discord.sh ]
+then
+/bin/bash ./discord.sh
+else
+echo -e "\ndiscord.sh not found!"
+fi
 
+# Install Spotify.
+if [ -f ./spotify.sh ]
+then
+/bin/bash ./spotify.sh
+else
+echo -e "\nspotify.sh not found!"
+fi
+
+# Get Hostname Information.
 OS=$(hostnamectl | grep Operating | awk -F ": " '{print $2}')
 
-if [[ "$OS" == *"MINT"* ]];
-then
-	echo "Flatpak comes pre-build with Linux Mint 18.3 and above!"
-	echo "Adding Flatpak repo for GNOME Authenticator as Local User"
-	su - $LOCALUSER -c "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"
-	echo "Installing GNOME Authenticator as Local User..."
-	su - $LOCALUSER -c "flatpak install -y flathub com.github.bilelmoussaoui.Authenticator"
-	echo "Done!"
-else
-	apt update
-	apt install flatpak -yqq
-	echo "Adding Flatpak repo for GNOME Authenticator as Local User"
-	su - $LOCALUSER -c "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"
-	echo "Installing GNOME Authenticator as Local User..."
-	su - $LOCALUSER -c "flatpak install -y flathub com.github.bilelmoussaoui.Authenticator"
-	echo "Done!"
-fi
-
+# If the OS is Debian, run the scripts.
 if [[ "$OS" == *"Debian"* ]]; then
-echo "Installing Wi-Fi and GPU Drivers"
-cp /etc/apt/sources.list /etc/apt/sources.list.save
-echo "" > /etc/apt/sources.list
-echo "
-#
 
-deb http://deb.debian.org/debian/ buster main contrib non-free
-deb-src http://deb.debian.org/debian/ buster main contrib non-free
+	# Install the packages.
+	if [ -f ./pkglist.txt ]
+	then
+		xargs apt install -yqq < pkglist.txt
+	else
+		echo -e "\npkglist.txt not found!"
+		sleep 1
+	fi
 
-deb http://security.debian.org/debian-security buster/updates main contrib non-free
-deb-src http://security.debian.org/debian-security buster/updates main contrib non-free
+	# Install NVIDIA Drivers
+	if [ -f ./nvidia.sh ]
+	then
+		/bin/bash ./nvidia.sh
+	else
+		echo -e "\nnvidia.sh not found!"
+		sleep 1
+	fi
 
-# buster-updates, previously known as 'volatile'
-deb http://deb.debian.org/debian/ buster-updates main contrib non-free
-deb-src http://deb.debian.org/debian/ buster-updates main contrib non-free
-
-" >> /etc/apt/sources.list
-apt update
-apt install broadcom-sta-dkms bumblebee-nvidia primus libgl1-nvidia-glx -yqq
-usermod -aG bumblebee $LOCALUSER
 fi
 
-# Clean and reboot now:
-apt clean && apt autoclean && apt autoremove -y
-echo $'\n'$"*** All done! Please reboot now. ***"
-exit
+echo -e "Please do not forget to reboot now!"
+echo -e "Also, execute localdebs and authenticator when in need"
+#EOF
